spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/billstack_db
spring.datasource.username=root
spring.datasource.password=Sharvari@10
spring.jpa.hibernate.ddl-auto=update
